# Generated by Django 3.2.9 on 2021-11-19 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20211119_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='message.user'),
        ),
    ]
