# Generated by Django 3.2.9 on 2021-11-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_message_sender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserMessage',
        ),
    ]
