# Generated by Django 3.2.9 on 2021-11-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0012_alter_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=50),
        ),
    ]
