# Generated by Django 3.2.9 on 2021-11-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0014_message_isread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='isRead',
            new_name='read',
        ),
    ]
