# Generated by Django 3.2.9 on 2021-11-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0015_rename_isread_message_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
